create database Hands_on

use Hands_on

--1. write a SQL query to find all the orders issued by the salesman 'Paul Adam'. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
select * 
from Orders
where Salesman_id in (Select Salesman_id from Salesman where name='Paul Adam')

--2. write a SQL query to find all the orders, which are generated by those salespeople, who live in the city of London.Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
select *
from Orders
where Salesman_id in (select Salesman_id from Salesman where City='London')

--3. write a SQL query to find the orders generated by the salespeople who works for customers whose id is 3007. Return ord_no, purch_amt, ord_date, customer_id, salesman_id. A customer can works only with a salespeople
select *
from Orders
where Customer_id in (select Customer_id from Customer where Customer_id=3007)

--4. write a SQL query to find the order values greater than the average order value of 10th October 2012. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
select *
from Orders
where Purch_amt>(select avg(Purch_amt) as 'Avg_Purch' from Orders Where Ord_date='2012-10-10')

--5. write a SQL query to find all the orders generated in New York city. Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
select *
from Orders
where Salesman_id in (select Salesman_id from Salesman where City='New York')

--6. write a SQL query to find the salespeople who had more than one customer. Return salesman_id and name.
select Salesman_id,name
from Salesman a
where 1<(Select count(*) from Customer where Salesman_id=a.Salesman_id)

--7. write a SQL query to find those orders, which are higher than average amount of the orders. Return ord_no, purch_amt, ord_date, customer_id and salesman_id
select *
From Orders
where Purch_amt>(Select avg(Purch_amt) from Orders)

--8. Write a query to find the sums of the amounts from the orders table, grouped by date, eliminating all those dates where the sum was not at least 1000.00 above the maximum order amount for that date
select ord_date, sum(Purch_amt)
From Orders a
Group by Ord_date
having sum(purch_amt)>(select 1000.00 + max(Purch_amt) from Orders b where a.Ord_date=b.Ord_date)

--9. Write a query to extract all data from the customer table if and only if one or more of the customers in the customer table are located in London.
select *
From Customer
where City in(select city from Customer where City='London')

--10. write a SQL query to find the salespeople who deal multiple customers. Return salesman_id, name, city and commission.
select Salesman_id,name,City,Commission
from Salesman a
where 1<(select count(*) from Customer b where a.Salesman_id=b.Salesman_id)
